MainLayout:

<MainLayout>:
	orientation : "vertical"
	BoxLayout : 
		orientation : 'horizontal'
		pos_hint : { "x" : .0 , "y" : .0}
		Button:
			size_hint : .5 , None 
			text : "8 PUZZLE"
			color : "white"
			pos : ""
		Label :
			text : "8 Puzzle AI"
			size_hint : 1 , .5 
	
	
	Button : 
		text : "a7a b2a"
	

<MainWidget>:
	Label:
		text : "8 PUZZLE"
		color : "white"
		size : "200dp" , "100dp"
		pos : "320dp" , "300dp"
	Button : 
		text : "a7a b2a"
		